# In-Class Exercise: Data Exploration

This exercise gives you practice in data explorating activities including reading, inspecting, subsetting, editing, summarizing, and visualizing data. Use the dataset 'tech_companies.csv' for this exercise. 

Dataset file: `tech_companies.csv`

Columns:
- `Company`: Company name
- `Industry`: Industry sector
- `Revenue`: Annual revenue in dollars
- `Profit_Margin`: Profit margin percentage
- `Employees`: Number of employees

## 1) Setup
**Question:** Import the required libraries: `numpy`, `pandas`, and `matplotlib.pyplot`.

In [1]:
import os
os.chdir('../')

In [2]:
# Your code here
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 2) Reading Data
**Question:**
A. Use `pd.read_csv()` to load `tech_companies.csv` into a DataFrame called `companies`.
B. Print the first five rows.

In [3]:
# A. Read CSV
companies=pd.read_csv('Datasets/tech_companies.csv')

# B. Head of data
companies.head(5)

     Company    Industry      Revenue  Profit_Margin  Employees
0  Company_1          AI  647800000.0          12.58        896
1  Company_2          AI  604500000.0          36.37       2579
2  Company_3  E-commerce  600560000.0          19.21       3408
3  Company_4     FinTech  758590000.0          20.01        250
4  Company_5  Healthcare  659730000.0          36.26       4816

## 3) Inspecting Data
**Question:**
A. Print the structure of the DataFrame using `.info()`.
B. Display the data types of each column.
C. Generate summary statistics with `.describe(include='all')`.
D. Check the shape, columns, and index of the DataFrame.

In [4]:
# A. info()
print(companies.info())

# B. dtypes
print(companies.dtypes)

# C. describe
print(companies.describe())

# D. shape, columns, index
print(companies.shape,companies.columns,companies.index)

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company        30 non-null     str
 1   Industry       30 non-null     str
 2   Revenue        30 non-null     float64
 3   Profit_Margin  30 non-null     float64
 4   Employees      30 non-null     int64
dtypes: float64(2), int64(1), str(2)
memory usage: 1.3 KB
None
Company              str
Industry             str
Revenue          float64
Profit_Margin    float64
Employees          int64
dtype: object
            Revenue  Profit_Margin    Employees
count  3.000000e+01      30.000000    30.000000
mean   5.083677e+08      25.382667  2268.733333
std    1.537697e+08       9.096488  1468.971982
min    2.762200e+08       7.070000   250.000000
25%    3.786600e+08      19.202500   900.500000
50%    4.922750e+08      25.400000  2327.000000
75%    6.370325e+08      34.037500  3522.500000
max    8.705300e+08      39.480000  4816.000000
(30, 5) Index(['Company', 'Industry', 'Revenue', 'Profit_Margin', 'Employees'], dtype='str') RangeIndex(start=0, stop=30, step=1)

## 4) Subsetting Data
**Question:**
A. Select only the `Company` column.
B. Select both `Revenue` and `Profit_Margin`.
C. Slice the first 10 rows.
D. Select rows where `Profit_Margin > 25`.

In [12]:
# A. one column
print(companies.loc[:,'Company'])

# B. two columns
print(companies.loc[:,['Revenue','Profit_Margin']])

# C. first 10 rows
print(companies.iloc[10,:])

# D. filter condition
print(companies[companies.Profit_Margin>25])

0      Company_1
1      Company_2
2      Company_3
3      Company_4
4      Company_5
5      Company_6
6      Company_7
7      Company_8
8      Company_9
9     Company_10
10    Company_11
11    Company_12
12    Company_13
13    Company_14
14    Company_15
15    Company_16
16    Company_17
17    Company_18
18    Company_19
19    Company_20
20    Company_21
21    Company_22
22    Company_23
23    Company_24
24    Company_25
25    Company_26
26    Company_27
27    Company_28
28    Company_29
29    Company_30
Name: Company, dtype: str
        Revenue  Profit_Margin
0   647800000.0          12.58
1   604500000.0          36.37
2   600560000.0          19.21
3   758590000.0          20.01
4   659730000.0          36.26
5   358460000.0           7.07
6   648940000.0          14.59
7   870530000.0          15.80
8   533940000.0          31.72
9   678900000.0          34.03
10  427870000.0          24.12
11  511410000.0          22.11
12  370260000.0          35.01
13  458680000.0          39.48
14  486250000.0          32.58
15  395250000.0          16.08
16  309200000.0          34.30
17  336610000.0          23.81
18  373130000.0          26.29
19  366640000.0          27.75
20  748480000.0          25.00
21  660590000.0          19.20
22  523190000.0          37.08
23  417350000.0          12.17
24  498300000.0          19.67
25  397790000.0          13.01
26  276220000.0          35.26
27  409620000.0          25.80
28  604730000.0          34.04
29  317510000.0          31.08
Company           Company_11
Industry                  AI
Revenue          427870000.0
Profit_Margin          24.12
Employees               3551
Name: 10, dtype: object
       Company    Industry      Revenue  Profit_Margin  Employees
1    Company_2          AI  604500000.0          36.37       2579
4    Company_5  Healthcare  659730000.0          36.26       4816
8    Company_9     FinTech  533940000.0          31.72       3928
9   Company_10      Gaming  678900000.0          34.03        290
12  Company_13      Gaming  370260000.0          35.01       3160
13  Company_14          AI  458680000.0          39.48        463
14  Company_15      Gaming  486250000.0          32.58       3818
16  Company_17  Healthcare  309200000.0          34.30       1344
18  Company_19      Gaming  373130000.0          26.29       3437
19  Company_20  E-commerce  366640000.0          27.75        277
22  Company_23          AI  523190000.0          37.08       4689
26  Company_27     FinTech  276220000.0          35.26        868
27  Company_28          AI  409620000.0          25.80       2075
28  Company_29          AI  604730000.0          34.04       3819
29  Company_30  Healthcare  317510000.0          31.08       2877

## 5) Editing Data
**Question:**
A. Create a new column `Revenue_Millions` by dividing `Revenue` by 1e6.
B. Rename `Profit_Margin` to `ProfitPct`.
C. Drop the `Employees` column.

In [16]:
# A. new column

# B. rename column


# C. drop column

(
    companies
        .assign(Revenue_Millions=companies.Revenue/1e6)
        .rename({'Profit_Margin':'ProfitPct'},axis=1)
        .drop(labels='Employees',axis=1)
)

       Company    Industry      Revenue  ProfitPct  Revenue_Millions
0    Company_1          AI  647800000.0      12.58            647.80
1    Company_2          AI  604500000.0      36.37            604.50
2    Company_3  E-commerce  600560000.0      19.21            600.56
3    Company_4     FinTech  758590000.0      20.01            758.59
4    Company_5  Healthcare  659730000.0      36.26            659.73
5    Company_6      Gaming  358460000.0       7.07            358.46
6    Company_7          AI  648940000.0      14.59            648.94
7    Company_8     FinTech  870530000.0      15.80            870.53
8    Company_9     FinTech  533940000.0      31.72            533.94
9   Company_10      Gaming  678900000.0      34.03            678.90
10  Company_11          AI  427870000.0      24.12            427.87
11  Company_12     FinTech  511410000.0      22.11            511.41
12  Company_13      Gaming  370260000.0      35.01            370.26
13  Company_14          AI  458680000.0      39.48            458.68
14  Company_15      Gaming  486250000.0      32.58            486.25
15  Company_16     FinTech  395250000.0      16.08            395.25
16  Company_17  Healthcare  309200000.0      34.30            309.20
17  Company_18     FinTech  336610000.0      23.81            336.61
18  Company_19      Gaming  373130000.0      26.29            373.13
19  Company_20  E-commerce  366640000.0      27.75            366.64
20  Company_21     FinTech  748480000.0      25.00            748.48
21  Company_22  E-commerce  660590000.0      19.20            660.59
22  Company_23          AI  523190000.0      37.08            523.19
23  Company_24     FinTech  417350000.0      12.17            417.35
24  Company_25          AI  498300000.0      19.67            498.30
25  Company_26          AI  397790000.0      13.01            397.79
26  Company_27     FinTech  276220000.0      35.26            276.22
27  Company_28          AI  409620000.0      25.80            409.62
28  Company_29          AI  604730000.0      34.04            604.73
29  Company_30  Healthcare  317510000.0      31.08            317.51

## 6) Summarizing Data
**Question:**
A. Compute the average profit margin.
B. Find the maximum revenue and the company that earned it.
C. Group companies by `Industry` and compute their mean revenue.

In [22]:
# A. average profit margin
print(companies.Profit_Margin.mean())

# B. max revenue and company
print(companies.Revenue.max(),companies[companies.Revenue==companies.Revenue.max()]['Company'])

# C. group by industry
print(companies.groupby(by='Industry').agg({'Revenue':'mean'}))

25.382666666666662
870530000.0 7    Company_8
Name: Company, dtype: str
                 Revenue
Industry
AI          5.221420e+08
E-commerce  5.425967e+08
FinTech     5.387089e+08
Gaming      4.534000e+08
Healthcare  4.288133e+08

## 7) Visualization
**Question:**
A. Create a histogram of `ProfitPct`.
B. Create a scatter plot of `Revenue` vs. `ProfitPct`.
C. Add axis labels and a title.

In [ ]:
# A. histogram


# B. scatter plot


# C. labels and title

## 8) Challenge
**Question:**
Using the dataset, answer:
- Do larger companies (more employees) tend to have higher revenues?
- Support your answer with both a visualization and a short written explanation.

In [ ]:
# Your analysis code here